# Generated by Django 5.2.4 on 2025-10-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gacha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("game", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("urgency", models.FloatField()),
            ],
        ),
    ]
